#+TITLE: CS554 Final Project: Client Connect
#+OPTIONS: toc:nil num:nil
#+STARTUP: noindent showall

* Group Members
- Khayyam Saleem, Michael Iacona, Maxwell Melo, Annie Topoleski

* Development Instructions
- Create a .env file. For non-prod, you can just rename ~.env.sample~ to ~.env~
- Ensure that you have ~nodemon~, ~yarn~, and ~mongod~ installed
- Run these commands:
    #+BEGIN_SRC bash
    yarn install
    git checkout <name>-<feature> # e.g. ham-chat-client
    yarn start
    #+END_SRC
- To work on backend, work in server directory, and test with Postman or curl or httpie before implementing into react front-end
- To work on frontend, implement components in ~components~ directory and create pages in ~pages~ directory. Use `~` for absolute imports. Follow the example of the ~Login~ component and ~Login~ page. Not each component needs to have its own page. Communicate with the backend using ~isomorphic-unfetch~. Refer to ~docs/strats.org~ or Khayyam Saleem for questions or pair-programming requests.

* Stack
- mongo, express, react (Next.js), node *(MERN)*
- socket.io for messaging
- redis for chat caching
- mongoose for schema definition
- Semantic UI for rendering
- winston for logging
